#!bin/bash

sudo apt-get update

if ! which nvim; then
    echo "Neovim not found, installing Neovim..."
    sudo snap install nvim --classic
fi

mkdir -p ~/.config/nvim
cp -r ~/dotfiles/init.lua/* ~/.config/nvim

git clone --depth 1 https://github.com/wbthomason/packer.nvim\
 ~/.local/share/nvim/site/pack/packer/start/packer.nvim


